version: '3.7'

services:
  php:
    build: ./docker/php
    container_name: plevent-php
    restart: on-failure
    volumes:
      - ./:/var/www

  db:
    image: postgres:11.6
    container_name: back-db
    restart: on-failure
    environment:
      POSTGRES_DB: plevent-back
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: ./docker/nginx
    container_name: plevent-nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php

  adminer:
    image: adminer
    container_name: plevent-adminer
    restart: on-failure
    ports:
      - 8080:8080

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge